* mpd++
** TODO Add playlist-oriented facilities
** TODO Document all fields and functions using the documentation of the mpd protocol
* Search mode
** TODO Add a mode to select and visualize playlists
Playlists and queues are similar. The search window probably can run mostly unmodified for playlist requests.
** TODO Allow to save playlists and modify playlists
We just need a way to save the result window to a playlist.
** DONE Allow to see in a db search if the songs are inside the current playlist
CLOSED: [2013-09-30 lun. 00:15]
This is complicated since we don't have this information in the search result.

Maybe we could ask for the whole queue and remember its identifiers (this is whac ncmpcpp does, for instance), but this could be wrong if the queue changes and we're not notified. We could then make an idle event to know when the queue changes, but this small feature would get somewhat complicated and add some unneeded overload… But maybe we just don't need to always be up to date.

We can also use send_queue_changes_brief to know if some queue information changed which would probably be quite efficient.
** TODO Allow to use command lists to optimize bandwidth a little in some cases.
* General
** TODO Close tmpc when the focus is lost
This could or could not be a good idea. Since tmpc typically does not appear as a top level window, it can be tricky to remember if one instance is currently open if its behind something else.

On the other hand, closing when focus is lost would make it annoying to have some focus-stealing app running.
