.\" Manpage for tmpc.
.\" Contact gclement@baobob.org.in to correct errors or typos.
.TH man 1 "12 Feb 2015" "1.0.1" "tmpc man page"
.SH NAME
tmpc \- Little mpd frontend
.SH SYNOPSIS
tmpc [--current] [--host host] [--port port]
.SH DESCRIPTION
tmpc is a small mpd frontend that is quick to load and can be bound to
hotkeys.
.SH OPTIONS
Available options are as follows:
.TP
.B --current, -c
Puts tmpc into "current song" mode. In this mode, the current song is
printed, with a progress bar and some information.
.TP
.B --host host -hhost
Defines the host that will be used to connect to mpd.
.TP
.B --port port -pport
Defiles the port that will be used to connect to mpd.
.SH ENVIRONMENT VARIABLES
The following environment variables can be used to tweak the behaviour of qimaptray:
.TP
.B MPD_HOST
Defines the host that will be used to connect to mpd.
.TP
.B MPD_PORT
Defines the port that will be used to connect to mpd.
.SH KEY BINDINGS
Here is a list of available keys in search mode:
.TP
.B F10
Toggle current song mode
.TP
.B Return
Play the selected song, then exit (except if current song is shown)
.TP
.B Space
Queue the selected song if it isn't already.
.TP
.B Ctrl-O
Add the current search to the play queue.
.TP
.B Ctrl-P
Clears the play queue.
.SH BUGS
The list of bugs can be accessed at https://github.com/guillaumecl/tmpc/issues
.SH AUTHOR
Guillaume Clement (gclement@baobob.org)
